version: "3"

services:
  db:
    container_name: database
    restart: always
    image: db-sopes
    ports:
      - "3306:3306"
    expose:
      - "3306"

  grpc-server:
    container_name: ruta1-server
    restart: always
    build: ./grpc-server
    image: grpc-server
    ports:
      - "50051:50051"
    depends_on:
      - db
    links:
      - db
  
  grpc-client:
    container_name: ruta1-client
    restart: always
    build: ./grpc-client
    image: grpc-client
    ports:
      - "4000:4000"
    depends_on:
      - grpc-server
    links:
      - grpc-server