version: '3' # versión de docker 

# ===== BASE DE DATOS =====
services:
  dbmysql:
    container_name: dbmysql
    restart: always
    build: ./mysql/
    image: gerson7w7/mysql_proyecto1
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db_data:/var/lib/mysql

  dbredis:
    container_name: dbredis
    restart: always
    build: ./redis/
    image: gerson7w7/redis_proyecto1
    ports:
      - '6379:6379'
    expose:
      - '6379'

# ===== GRPC =====
  grpc-server:
    container_name: grpc-server
    restart: always
    build: ./ruta1/grpc-server/
    image: gerson7w7/grpc-server_proyecto1
    ports:
      - "50051:50051"
    depends_on:
      - dbmysql
    links:
      - dbmysql
  
  grpc-client:
    container_name: grpc-client
    restart: always
    build: ./ruta1/grpc-client/ 
    image: gerson7w7/grpc-client_proyecto1
    ports:
      - "4000:4000"
    depends_on:
      - grpc-server
    links:
      - grpc-server

# ===== PUB Y SUB =====
  pub:
    container_name: pub
    restart: always
    build: ./ruta2/pub/ 
    image: gerson7w7/pub_proyecto1
    ports:
      - "4100:4100"
    depends_on:
      - dbredis
    links:
      - dbredis
  
  sub:
    container_name: sub
    restart: always
    build: ./ruta2/sub/ 
    image: gerson7w7/sub_proyecto1
    depends_on:
      - dbredis
    links:
      - dbredis
      - dbmysql

# ===== API =====
  api:
    container_name: api 
    restart: always 
    build: ./api/
    image: gerson7w7/api_proyecto1
    ports:
      - "5000:5000"
    depends_on:
      - dbmysql # el servicio api depende de bd 
      - dbredis
    links:
      - dbmysql
      - dbredis 

# ===== FRONTEND =====
  frontend:
    container_name: frontend 
    restart: always 
    build: ./frontend/
    image: gerson7w7/frontend_proyecto1
    ports:
      - "3000:3000"
    depends_on:
      - api # el servicio backend depende de bd 
    links:
      - api 

volumes:
  db_data: