version: '3' # versión de docker 

services:
  db:
    container_name: dbproyecto
    restart: always
    build: ./mysql/
    image: gerson7w7/bd_proyecto1
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db_data:/var/lib/mysql

  api:
    container_name: api 
    restart: always 
    build: ./api/
    image: gerson7w7/api_proyecto1
    ports:
      - "5000:5000"
    depends_on:
      - db # el servicio api depende de bd 
    links:
      - db 

  frontend:
    container_name: frontend 
    restart: always 
    build: ./frontend/
    image: gerson7w7/frontend_proyecto1
    ports:
      - "3000:3000"
    depends_on:
      - api # el servicio backend depende de bd 
    links:
      - api 

volumes:
  db_data: