version: '3' # versión de docker 

services:
  dbmysql:
    container_name: dbmysql
    restart: always
    build: ./mysql/
    image: gerson7w7/mysql_proyecto1
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db_data:/var/lib/mysql

  dbredis:
    container_name: dbredis
    restart: always
    build: ./redis/
    image: gerson7w7/redis_proyecto1
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - ./db_data_redis:/data

  api:
    container_name: api 
    restart: always 
    build: ./api/
    image: gerson7w7/api_proyecto1
    ports:
      - "5000:5000"
    depends_on:
      - dbmysql # el servicio api depende de bd 
      - dbredis
    links:
      - dbmysql
      - dbredis 

  frontend:
    container_name: frontend 
    restart: always 
    build: ./frontend/
    image: gerson7w7/frontend_proyecto1
    ports:
      - "3000:3000"
    depends_on:
      - api # el servicio backend depende de bd 
    links:
      - api 

volumes:
  db_data:
  db_data_redis: