apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: balanceador
  namespace: p1
spec:
  rules:
    - host: proyecto1-so1.com
      http:
        paths:
          - backend:
              service:
                name: grpc-client-svc
                port:
                  number: 4000
            path: /add-voto
            pathType: Prefix
          - backend:
              service:
                name: pub-redis-svc
                port:
                  number: 4100
            path: /add-voto
            pathType: Prefix
