# espacio donde se crearan todos los pods
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: proyecto1 # nombre del namespace
---
# servicio para conectarse entre pods y fuera de los mismos
apiVersion: v1
kind: Service
metadata:
  name: mysql # nombre del servicio
  namespace: proyecto1
spec:
  type: ClusterIP
  selector:
    app: mysql # quien usara el servicio
  ports:
    - name: http
      port: 3306
      targetPort: 3306
---
# volumen para persistencia de datos
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# deployment para desplegar nuestros pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql # nombre del deployment
  namespace: proyecto1
  labels:
    app: mysql # label del deployment (se podría omitir)
spec:
  replicas: 1 # replicas del pod
  selector:
    matchLabels:
      app: mysql
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # uso de volumen
      volumes:
      - name: mysql-persistent-storage # nombre del volumen
        persistentVolumeClaim:
          claimName: mysql-pv-claim # volumen a usar
      # contenedores del pod
      containers:
      - name: mysql # nombre del contenedor
        image: gerson7w7/mysql_proyecto1
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql